# Generated by Django 3.1.4 on 2021-05-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tontine', '0011_auto_20210504_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontinemember')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontine')),
            ],
        ),
    ]
