# Generated by Django 3.1.4 on 2021-05-26 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tontine', '0012_auto_20210526_1342'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingcard',
            name='asistant_auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_ass_auditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votingcard',
            name='asistant_secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_ass_ecretery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votingcard',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_auditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votingcard',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='votingcard',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_president', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votingcard',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_secretary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votingcard',
            name='treasurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_treasurer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontine')),
            ],
        ),
        migrations.AddField(
            model_name='votingcard',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.election'),
        ),
    ]
