# Generated by Django 3.1.4 on 2021-05-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210526_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingcard',
            name='tontine',
        ),
    ]
