# Generated by Django 3.1.4 on 2021-03-24 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tontine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slogan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TontineMemeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('number_of_shares', models.IntegerField()),
                ('status', models.CharField(choices=[('PR', 'President'), ('TR', 'Treasurer'), ('SE', 'Secretary'), ('ASE', 'Asistant Secretary'), ('AU', 'Auditor'), ('AAU', 'Asistant Auditor'), ('MEM', 'Member')], default='MEM', max_length=5)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField()),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontine')),
            ],
            options={
                'verbose_name': 'Tontine Rule',
                'verbose_name_plural': 'Tontine Rules',
            },
        ),
    ]
