# Generated by Django 3.1.4 on 2021-03-24 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tontine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TontineMemeber',
            new_name='TontineMember',
        ),
    ]
