# Generated by Django 3.1.4 on 2021-03-24 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tontine', '0002_auto_20210324_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tontinemember',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tontinemember',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='tontinemember',
            name='phone',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
