# Generated by Django 3.1.4 on 2021-03-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0003_auto_20210324_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='yaounde', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default='2021-04-07'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='tontine@gmail.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='0000', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='Teacher', max_length=100),
        ),
    ]
