# Generated by Django 3.1.4 on 2021-04-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0004_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tontine',
            name='slug',
        ),
    ]
