# Generated by Django 3.1.4 on 2021-03-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0004_auto_20210325_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
