# Generated by Django 3.1.4 on 2021-05-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0007_auto_20210401_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name': 'Reqeusts', 'verbose_name_plural': 'Requests'},
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sent_from', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontinemember')),
            ],
        ),
    ]
