# Generated by Django 3.1.4 on 2021-05-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0009_auto_20210504_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='tontine',
            field=models.CharField(max_length=200),
        ),
    ]
