# Generated by Django 3.1.4 on 2021-05-26 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0011_auto_20210504_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tontine',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
